# https://hub.docker.com/layers/flyio/postgres-flex/15.3/images/sha256-44b698752cf113110f2fa72443d7fe452b48228aafbb0d93045ef1e3282360a6
version: '3.9'

services:
    postgres:
        container_name: postgres
        image: postgres:15.3-alpine3.18
        ports:
            - 5432:5432
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=example_password
            - POSTGRES_DB=api_thesammy2010_com
