// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/v1/squash/player.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SquashPlayerService_CreateSquashPlayer_FullMethodName = "/SquashPlayerService/CreateSquashPlayer"
	SquashPlayerService_GetSquashPlayer_FullMethodName    = "/SquashPlayerService/GetSquashPlayer"
	SquashPlayerService_ListSquashPlayers_FullMethodName  = "/SquashPlayerService/ListSquashPlayers"
	SquashPlayerService_UpdateSquashPlayer_FullMethodName = "/SquashPlayerService/UpdateSquashPlayer"
	SquashPlayerService_DeleteSquashPlayer_FullMethodName = "/SquashPlayerService/DeleteSquashPlayer"
	SquashPlayerService_SignUp_FullMethodName             = "/SquashPlayerService/SignUp"
)

// SquashPlayerServiceClient is the client API for SquashPlayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SquashPlayerServiceClient interface {
	// Deprecated: Do not use.
	CreateSquashPlayer(ctx context.Context, in *CreateSquashPlayerRequest, opts ...grpc.CallOption) (*CreateSquashPlayerResponse, error)
	GetSquashPlayer(ctx context.Context, in *GetSquashPlayerRequest, opts ...grpc.CallOption) (*GetSquashPlayerResponse, error)
	ListSquashPlayers(ctx context.Context, in *ListSquashPlayersRequest, opts ...grpc.CallOption) (*ListSquashPlayersResponse, error)
	UpdateSquashPlayer(ctx context.Context, in *UpdateSquashPlayerRequest, opts ...grpc.CallOption) (*UpdateSquashPlayerResponse, error)
	DeleteSquashPlayer(ctx context.Context, in *DeleteSquashPlayerRequest, opts ...grpc.CallOption) (*DeleteSquashPlayerResponse, error)
	SignUp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CreateSquashPlayerResponse, error)
}

type squashPlayerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSquashPlayerServiceClient(cc grpc.ClientConnInterface) SquashPlayerServiceClient {
	return &squashPlayerServiceClient{cc}
}

// Deprecated: Do not use.
func (c *squashPlayerServiceClient) CreateSquashPlayer(ctx context.Context, in *CreateSquashPlayerRequest, opts ...grpc.CallOption) (*CreateSquashPlayerResponse, error) {
	out := new(CreateSquashPlayerResponse)
	err := c.cc.Invoke(ctx, SquashPlayerService_CreateSquashPlayer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squashPlayerServiceClient) GetSquashPlayer(ctx context.Context, in *GetSquashPlayerRequest, opts ...grpc.CallOption) (*GetSquashPlayerResponse, error) {
	out := new(GetSquashPlayerResponse)
	err := c.cc.Invoke(ctx, SquashPlayerService_GetSquashPlayer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squashPlayerServiceClient) ListSquashPlayers(ctx context.Context, in *ListSquashPlayersRequest, opts ...grpc.CallOption) (*ListSquashPlayersResponse, error) {
	out := new(ListSquashPlayersResponse)
	err := c.cc.Invoke(ctx, SquashPlayerService_ListSquashPlayers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squashPlayerServiceClient) UpdateSquashPlayer(ctx context.Context, in *UpdateSquashPlayerRequest, opts ...grpc.CallOption) (*UpdateSquashPlayerResponse, error) {
	out := new(UpdateSquashPlayerResponse)
	err := c.cc.Invoke(ctx, SquashPlayerService_UpdateSquashPlayer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squashPlayerServiceClient) DeleteSquashPlayer(ctx context.Context, in *DeleteSquashPlayerRequest, opts ...grpc.CallOption) (*DeleteSquashPlayerResponse, error) {
	out := new(DeleteSquashPlayerResponse)
	err := c.cc.Invoke(ctx, SquashPlayerService_DeleteSquashPlayer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squashPlayerServiceClient) SignUp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CreateSquashPlayerResponse, error) {
	out := new(CreateSquashPlayerResponse)
	err := c.cc.Invoke(ctx, SquashPlayerService_SignUp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SquashPlayerServiceServer is the server API for SquashPlayerService service.
// All implementations should embed UnimplementedSquashPlayerServiceServer
// for forward compatibility
type SquashPlayerServiceServer interface {
	// Deprecated: Do not use.
	CreateSquashPlayer(context.Context, *CreateSquashPlayerRequest) (*CreateSquashPlayerResponse, error)
	GetSquashPlayer(context.Context, *GetSquashPlayerRequest) (*GetSquashPlayerResponse, error)
	ListSquashPlayers(context.Context, *ListSquashPlayersRequest) (*ListSquashPlayersResponse, error)
	UpdateSquashPlayer(context.Context, *UpdateSquashPlayerRequest) (*UpdateSquashPlayerResponse, error)
	DeleteSquashPlayer(context.Context, *DeleteSquashPlayerRequest) (*DeleteSquashPlayerResponse, error)
	SignUp(context.Context, *emptypb.Empty) (*CreateSquashPlayerResponse, error)
}

// UnimplementedSquashPlayerServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSquashPlayerServiceServer struct {
}

func (UnimplementedSquashPlayerServiceServer) CreateSquashPlayer(context.Context, *CreateSquashPlayerRequest) (*CreateSquashPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSquashPlayer not implemented")
}
func (UnimplementedSquashPlayerServiceServer) GetSquashPlayer(context.Context, *GetSquashPlayerRequest) (*GetSquashPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSquashPlayer not implemented")
}
func (UnimplementedSquashPlayerServiceServer) ListSquashPlayers(context.Context, *ListSquashPlayersRequest) (*ListSquashPlayersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSquashPlayers not implemented")
}
func (UnimplementedSquashPlayerServiceServer) UpdateSquashPlayer(context.Context, *UpdateSquashPlayerRequest) (*UpdateSquashPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSquashPlayer not implemented")
}
func (UnimplementedSquashPlayerServiceServer) DeleteSquashPlayer(context.Context, *DeleteSquashPlayerRequest) (*DeleteSquashPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSquashPlayer not implemented")
}
func (UnimplementedSquashPlayerServiceServer) SignUp(context.Context, *emptypb.Empty) (*CreateSquashPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}

// UnsafeSquashPlayerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SquashPlayerServiceServer will
// result in compilation errors.
type UnsafeSquashPlayerServiceServer interface {
	mustEmbedUnimplementedSquashPlayerServiceServer()
}

func RegisterSquashPlayerServiceServer(s grpc.ServiceRegistrar, srv SquashPlayerServiceServer) {
	s.RegisterService(&SquashPlayerService_ServiceDesc, srv)
}

func _SquashPlayerService_CreateSquashPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSquashPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquashPlayerServiceServer).CreateSquashPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquashPlayerService_CreateSquashPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquashPlayerServiceServer).CreateSquashPlayer(ctx, req.(*CreateSquashPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquashPlayerService_GetSquashPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSquashPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquashPlayerServiceServer).GetSquashPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquashPlayerService_GetSquashPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquashPlayerServiceServer).GetSquashPlayer(ctx, req.(*GetSquashPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquashPlayerService_ListSquashPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSquashPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquashPlayerServiceServer).ListSquashPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquashPlayerService_ListSquashPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquashPlayerServiceServer).ListSquashPlayers(ctx, req.(*ListSquashPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquashPlayerService_UpdateSquashPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSquashPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquashPlayerServiceServer).UpdateSquashPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquashPlayerService_UpdateSquashPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquashPlayerServiceServer).UpdateSquashPlayer(ctx, req.(*UpdateSquashPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquashPlayerService_DeleteSquashPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSquashPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquashPlayerServiceServer).DeleteSquashPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquashPlayerService_DeleteSquashPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquashPlayerServiceServer).DeleteSquashPlayer(ctx, req.(*DeleteSquashPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquashPlayerService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquashPlayerServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquashPlayerService_SignUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquashPlayerServiceServer).SignUp(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SquashPlayerService_ServiceDesc is the grpc.ServiceDesc for SquashPlayerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SquashPlayerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SquashPlayerService",
	HandlerType: (*SquashPlayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSquashPlayer",
			Handler:    _SquashPlayerService_CreateSquashPlayer_Handler,
		},
		{
			MethodName: "GetSquashPlayer",
			Handler:    _SquashPlayerService_GetSquashPlayer_Handler,
		},
		{
			MethodName: "ListSquashPlayers",
			Handler:    _SquashPlayerService_ListSquashPlayers_Handler,
		},
		{
			MethodName: "UpdateSquashPlayer",
			Handler:    _SquashPlayerService_UpdateSquashPlayer_Handler,
		},
		{
			MethodName: "DeleteSquashPlayer",
			Handler:    _SquashPlayerService_DeleteSquashPlayer_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _SquashPlayerService_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/squash/player.proto",
}
