// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/v1/squash/singles.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SquashSinglesGameService_CreateSquashSinglesGame_FullMethodName = "/SquashSinglesGameService/CreateSquashSinglesGame"
	SquashSinglesGameService_GetSquashSinglesGame_FullMethodName    = "/SquashSinglesGameService/GetSquashSinglesGame"
	SquashSinglesGameService_ListSquashSinglesGame_FullMethodName   = "/SquashSinglesGameService/ListSquashSinglesGame"
	SquashSinglesGameService_UpdateSquashSinglesGame_FullMethodName = "/SquashSinglesGameService/UpdateSquashSinglesGame"
)

// SquashSinglesGameServiceClient is the client API for SquashSinglesGameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SquashSinglesGameServiceClient interface {
	CreateSquashSinglesGame(ctx context.Context, in *CreateSquashSinglesGameRequest, opts ...grpc.CallOption) (*CreateSquashSinglesGameResponse, error)
	GetSquashSinglesGame(ctx context.Context, in *GetSquashSinglesGameRequest, opts ...grpc.CallOption) (*GetSquashSinglesGameResponse, error)
	ListSquashSinglesGame(ctx context.Context, in *ListSquashSinglesGameRequest, opts ...grpc.CallOption) (*ListSquashSinglesGameResponse, error)
	UpdateSquashSinglesGame(ctx context.Context, in *UpdateSquashSinglesGameRequest, opts ...grpc.CallOption) (*UpdateSquashSinglesGameResponse, error)
}

type squashSinglesGameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSquashSinglesGameServiceClient(cc grpc.ClientConnInterface) SquashSinglesGameServiceClient {
	return &squashSinglesGameServiceClient{cc}
}

func (c *squashSinglesGameServiceClient) CreateSquashSinglesGame(ctx context.Context, in *CreateSquashSinglesGameRequest, opts ...grpc.CallOption) (*CreateSquashSinglesGameResponse, error) {
	out := new(CreateSquashSinglesGameResponse)
	err := c.cc.Invoke(ctx, SquashSinglesGameService_CreateSquashSinglesGame_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squashSinglesGameServiceClient) GetSquashSinglesGame(ctx context.Context, in *GetSquashSinglesGameRequest, opts ...grpc.CallOption) (*GetSquashSinglesGameResponse, error) {
	out := new(GetSquashSinglesGameResponse)
	err := c.cc.Invoke(ctx, SquashSinglesGameService_GetSquashSinglesGame_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squashSinglesGameServiceClient) ListSquashSinglesGame(ctx context.Context, in *ListSquashSinglesGameRequest, opts ...grpc.CallOption) (*ListSquashSinglesGameResponse, error) {
	out := new(ListSquashSinglesGameResponse)
	err := c.cc.Invoke(ctx, SquashSinglesGameService_ListSquashSinglesGame_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squashSinglesGameServiceClient) UpdateSquashSinglesGame(ctx context.Context, in *UpdateSquashSinglesGameRequest, opts ...grpc.CallOption) (*UpdateSquashSinglesGameResponse, error) {
	out := new(UpdateSquashSinglesGameResponse)
	err := c.cc.Invoke(ctx, SquashSinglesGameService_UpdateSquashSinglesGame_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SquashSinglesGameServiceServer is the server API for SquashSinglesGameService service.
// All implementations should embed UnimplementedSquashSinglesGameServiceServer
// for forward compatibility
type SquashSinglesGameServiceServer interface {
	CreateSquashSinglesGame(context.Context, *CreateSquashSinglesGameRequest) (*CreateSquashSinglesGameResponse, error)
	GetSquashSinglesGame(context.Context, *GetSquashSinglesGameRequest) (*GetSquashSinglesGameResponse, error)
	ListSquashSinglesGame(context.Context, *ListSquashSinglesGameRequest) (*ListSquashSinglesGameResponse, error)
	UpdateSquashSinglesGame(context.Context, *UpdateSquashSinglesGameRequest) (*UpdateSquashSinglesGameResponse, error)
}

// UnimplementedSquashSinglesGameServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSquashSinglesGameServiceServer struct {
}

func (UnimplementedSquashSinglesGameServiceServer) CreateSquashSinglesGame(context.Context, *CreateSquashSinglesGameRequest) (*CreateSquashSinglesGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSquashSinglesGame not implemented")
}
func (UnimplementedSquashSinglesGameServiceServer) GetSquashSinglesGame(context.Context, *GetSquashSinglesGameRequest) (*GetSquashSinglesGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSquashSinglesGame not implemented")
}
func (UnimplementedSquashSinglesGameServiceServer) ListSquashSinglesGame(context.Context, *ListSquashSinglesGameRequest) (*ListSquashSinglesGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSquashSinglesGame not implemented")
}
func (UnimplementedSquashSinglesGameServiceServer) UpdateSquashSinglesGame(context.Context, *UpdateSquashSinglesGameRequest) (*UpdateSquashSinglesGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSquashSinglesGame not implemented")
}

// UnsafeSquashSinglesGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SquashSinglesGameServiceServer will
// result in compilation errors.
type UnsafeSquashSinglesGameServiceServer interface {
	mustEmbedUnimplementedSquashSinglesGameServiceServer()
}

func RegisterSquashSinglesGameServiceServer(s grpc.ServiceRegistrar, srv SquashSinglesGameServiceServer) {
	s.RegisterService(&SquashSinglesGameService_ServiceDesc, srv)
}

func _SquashSinglesGameService_CreateSquashSinglesGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSquashSinglesGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquashSinglesGameServiceServer).CreateSquashSinglesGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquashSinglesGameService_CreateSquashSinglesGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquashSinglesGameServiceServer).CreateSquashSinglesGame(ctx, req.(*CreateSquashSinglesGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquashSinglesGameService_GetSquashSinglesGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSquashSinglesGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquashSinglesGameServiceServer).GetSquashSinglesGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquashSinglesGameService_GetSquashSinglesGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquashSinglesGameServiceServer).GetSquashSinglesGame(ctx, req.(*GetSquashSinglesGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquashSinglesGameService_ListSquashSinglesGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSquashSinglesGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquashSinglesGameServiceServer).ListSquashSinglesGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquashSinglesGameService_ListSquashSinglesGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquashSinglesGameServiceServer).ListSquashSinglesGame(ctx, req.(*ListSquashSinglesGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquashSinglesGameService_UpdateSquashSinglesGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSquashSinglesGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquashSinglesGameServiceServer).UpdateSquashSinglesGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquashSinglesGameService_UpdateSquashSinglesGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquashSinglesGameServiceServer).UpdateSquashSinglesGame(ctx, req.(*UpdateSquashSinglesGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SquashSinglesGameService_ServiceDesc is the grpc.ServiceDesc for SquashSinglesGameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SquashSinglesGameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SquashSinglesGameService",
	HandlerType: (*SquashSinglesGameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSquashSinglesGame",
			Handler:    _SquashSinglesGameService_CreateSquashSinglesGame_Handler,
		},
		{
			MethodName: "GetSquashSinglesGame",
			Handler:    _SquashSinglesGameService_GetSquashSinglesGame_Handler,
		},
		{
			MethodName: "ListSquashSinglesGame",
			Handler:    _SquashSinglesGameService_ListSquashSinglesGame_Handler,
		},
		{
			MethodName: "UpdateSquashSinglesGame",
			Handler:    _SquashSinglesGameService_UpdateSquashSinglesGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/squash/singles.proto",
}
