"""go_heavier: add location table

Revision ID: 91bfced20867
Revises: fe7fff8220d2
Create Date: 2025-08-15 20:56:29.270137

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91bfced20867"
down_revision: Union[str, Sequence[str], None] = "fe7fff8220d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "address_country")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column(
            "address_country",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
