"""go_heavier: add exercises endpoint

Revision ID: 6f2dae00bb77
Revises: 06b584012527
Create Date: 2025-10-07 21:18:47.527120

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f2dae00bb77"
down_revision: Union[str, Sequence[str], None] = "06b584012527"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("muscle_group", sa.String(length=100), nullable=True),
        sa.Column("specific_muscle", sa.String(length=100), nullable=True),
        sa.Column("bipedal", sa.Boolean(), nullable=False),
        sa.Column("image_url", sa.String(length=512), nullable=True),
        sa.Column("free_weights", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exercises")
    # ### end Alembic commands ###
