"""go_heavier: locations: add postcode column

Revision ID: aa543e109b6f
Revises: 37b2d51b368c
Create Date: 2025-10-07 19:23:34.390437

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa543e109b6f"
down_revision: Union[str, Sequence[str], None] = "37b2d51b368c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column("address_postal_code", sa.String(length=8), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "address_postal_code")
    # ### end Alembic commands ###
