"""add enrichment fields to sessions

Revision ID: 4e479c5f65e3
Revises: 799aecc25605
Create Date: 2026-09-01 00:08:19.783404

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e479c5f65e3"
down_revision: Union[str, Sequence[str], None] = "799aecc25605"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("duration_minutes", sa.Integer(), nullable=True)
    )
    op.add_column(
        "sessions", sa.Column("calories_burned_kcal", sa.Integer(), nullable=True)
    )
    op.add_column("sessions", sa.Column("took_preworkout", sa.Boolean(), nullable=True))
    op.add_column("sessions", sa.Column("went_to_office", sa.Boolean(), nullable=True))
    op.add_column("sessions", sa.Column("sleep_hours", sa.Float(), nullable=True))
    op.add_column(
        "sessions", sa.Column("bed_time", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("sessions", sa.Column("sleep_score", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "sleep_score")
    op.drop_column("sessions", "bed_time")
    op.drop_column("sessions", "sleep_hours")
    op.drop_column("sessions", "went_to_office")
    op.drop_column("sessions", "took_preworkout")
    op.drop_column("sessions", "calories_burned_kcal")
    op.drop_column("sessions", "duration_minutes")
    # ### end Alembic commands ###
