"""add logo_url to locations

Revision ID: 4c0deee26f71
Revises: 9b3a6dc93a77
Create Date: 2026-08-22 15:28:58.610241

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c0deee26f71"
down_revision: Union[str, Sequence[str], None] = "9b3a6dc93a77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations", sa.Column("logo_url", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "logo_url")
    # ### end Alembic commands ###
